function info(chatID, pinMode) {
    if (pinMode == undefined) { pinMode = false }
    if (pinMode) {
        var sheetNumber = 2
    } else {
        var sheetNumber = 0
    }
    var chatID = String(chatID)
    var ssNew = SpreadsheetApp.openById(sheetID)
    var sheet = ssNew.getSheets()[sheetNumber]
    var range = sheet.getDataRange()
    var rules = range.getValues()
    var fromValue = 1
    var messages = []
    var toValue = rules.length
    var result = 0
    var message = ''
    for (i = fromValue; i < toValue; i++) {
        var chatid = String(rules[i][0])
        if (chatID == chatid) {
            result++
            if (result == 1) {
                message += 'Products being tracked in this chat '
                if (pinMode) {
                    message += 'through pincode mode '
                }
                message += ':\n\n'
            }
            if (pinMode) { var pincode = rules[i][ssVars[7]] }
            var uri = rules[i][ssVars[3]]
            var prevPrice = rules[i][ssVars[1]]
            var trackId = rules[i][ssVars[2]]
            var name = rules[i][ssVars[6]]
            if (uri.lastIndexOf('amazon.in') != -1) {
                var client = 'Amazon'
            } else if (uri.lastIndexOf('flipkart.com') != -1) {
                var client = 'Flipkart'
            } else {
                var client = 'Flipkart'
            }
            if (name == undefined || name == '') { name = 'Product' }
            var oStock = String(rules[i][ssVars[5]]).trim().toLocaleLowerCase() == 'true'
            if (oStock) { var stck = 'In Stock' } else { var stck = 'Unavailable' }
            var lastChecked = String(rules[i][ssVars[4]])
            message += `<b>${result}. <a href="${uri}">${name}</a></b>\n<b>Track ID :</b> <code>${trackId}</code>\nPrice : <code>Rs. ${inr(prevPrice)}</code>\n<b>Stock :</b> <code>${stck}</code>\n<b>Marketplace :</b> <code>${client}</code>\n<b>Last Checked :</b> <code>${convertTime(lastChecked)}</code>\n`
            if (pinMode) { message += `<b>Pincode :</b> <code>${pincode}</code>\n` }
            message += `<b>Stop Tracking :</b> /stop_${trackId}\n<b>View Product :</b> /show_${trackId}\n\n`
        }
        if ((i + 1) == toValue) {
            var after = Math.ceil((rules.length - 1) / batchSize) * trackAfter
            if (pinMode) {
                after = Math.ceil((rules.length - 1) / pincodeBatchSize) * pincodeTrackAfter
            }
            message += `<b>Currently we are tracking your products every <code>${after} minutes</code>!</b>\n\nGenerated by ${botName}`
        }
        if ((result % 8 == 0 || (i + 1) == toValue) && message != '') {
            messages.push(message)
            message = ''
        }
    }
    if (result > 0) {
        return messages
    } else {
        if (pinMode) { return [] }
        return ['No active trackings found in this chat!']
    }
}

function convertTime(str) {
    var date = new Date(str)
    var mnth = ("0" + (date.getMonth() + 1)).slice(-2)
    var day = ("0" + date.getDate()).slice(-2);
    var hours = date.getHours();
    var minutes = date.getMinutes();
    var ampm = hours >= 12 ? 'PM' : 'AM';
    hours = hours % 12;
    hours = hours ? hours : 12; // the hour '0' should be '12'
    minutes = minutes < 10 ? '0' + minutes : minutes;
    var strTime = hours + ':' + minutes + ' ' + ampm;
    return (strTime + ' (' + String([day, mnth, date.getFullYear()].join("/")) + ')');
}
