function search(keyword, data, mode, client) {
    var client_uri = 'flipkart'
    var exp = 'fks'
    switch (client) {
        case 'Amazon':
            client_uri = 'amazon-scraper'
            exp = 'ams'
            break;
        default:
            client_uri = 'flipkart'
            exp = 'fks'
    }
    const searchApi = `https://${client_uri}.dvishal485.workers.dev/search/`
    var searchLink = searchApi + keyword
    var json = JSON.parse(String(UrlFetchApp.fetch(searchLink)))
    var searchList = json.result
    // sendReport(searchLink)
    // sendReport(searchList.length)
    var o = 'ℹ️ To get details any of the following product just send it\'s URL to me.\nI can also assist you with its price tracking when you send the URL\n\nGenerated by ' + botName
    var footer = o
    var res = '🔎 Search result for <code>' + keyword + '</code>\n\n', s = false
    var key = searchList.length
    var expandable = false
    try {
        if (key != 0) {
            if (mode == 'compact' && key > 12) { key = 12, expandable = true }
            if (keyword == '' && mode == 'compact') {
                res = '🔎 Exploring random products!\n\n'
                if (searchList.length > 20) { key = 20 }
            } else if (keyword == '' && mode == 'split') { footer = o }
            if (mode == 'split') { s = true }
            for (var k = 0; k < key; k++) {
                var name = null, link = null, cprice = null, d = null, oprice = null
                name = searchList[k].name
                link = searchList[k].link
                cprice = searchList[k].current_price
                d = searchList[k].discounted
                oprice = searchList[k].original_price
                if (name.split('<').length > 1) { name = link.split('&')[0] }
                var cp = ''
                if (cprice > 0) { cp += '\nCurrent Price : Rs.' + inr(cprice) } else { cp = '\nCan\'t find price!' }
                if (d && cprice > 0) { cp += '\nOriginal Price : Rs.' + inr(oprice) }
                res += (k + 1) + '. <a href="' + link + '">' + name + '</a>' + cp + '\n\n'
                // sendReport((k + 1) + ' , ' + key)
                // sendReport(String((s && ((k + 1) % 8 == 0)) || (k + 1) == key))
                // sendReport(res)
                if ((s && ((k + 1) % 8 == 0)) || (k + 1) == key) {
                    if (s) { var page = `ℹ️ Page ${Math.ceil((k + 1) / 8)}` } else { var page = `Open Search in ${client}` }
                    var keyboardButtons = [
                        { "text": page, "url": json.fetch_from }
                    ]
                    if ((k + 1) == key) {
                        if (expandable) {
                            if (keyword == '') { cb = '/all' } else { var cb = `/${exp} ${keyword}` }
                            keyboardButtons.push({ "text": 'Show more results', "callback_data": cb })
                        }
                        sendButtonMessage(res + footer, data, null, keyboardButtons)
                    } else {
                        sendButtonMessage(res, data, null, keyboardButtons)
                        res = ''
                    }
                }
            }
        } else {
            sendMessage('🔎 No results found for <code>' + keyword + '</code>', data)
        }
    } catch (er) {
        sendMessage('🔎 Some error occured while searching')
        sendReport('Error while searching')
        sendReport(Error(er).message)
    }
}

function valid(x) {
    return (x != undefined && x != null)
}