function spec(link, spec, data, searhNpull) {
    try {
        var json = fetchSpecs(spec, link), name = json.name, price = inr(json.current_price), stock = json.in_stock
        var url = json.share_url, dspec = json.desired_specs
        // var oPrice = inr(json.original_price), discount = json.discount_percent, discountAmount = json.original_price - json.current_price, rating = json.rating, fassured = json.f_assured, f=''
        var specs = ''
        if (spec == '&') { var r = 'Showing all ' } else { var r = 'Required' }
        if (String(url).toLowerCase().split('login').length > 1 || link.split('dl.flipkart.com/').length > 1) { url = link }
        if (dspec != undefined) {
            // sendReport('link :' + link)
            // sendReport('spec : ' + spec)
            // sendReport('json :' + JSON.stringify(json))
            if (dspec.length != 0) {
                specs += '\n\n<b>' + name + '</b>\n' + '💵 Current Price : Rs. ' + price +
                    '\n\n✏️ ' + r + ' Specifications : '
                for (var i = 0; i < dspec.length; i++) {
                    var pr = dspec[i].property
                    var pd = dspec[i].value
                    var add = '\n<b>' + (i + 1) + '. ' + pr + '</b> : ' + pd
                    if ((specs + add).length > 4010) {
                        sendMessage(specs, data)
                        specs = '<b>' + (i + 1) + '. ' + pr + '</b> : ' + pd
                    } else {
                        specs += add
                    }
                    if ((i + 1) % 60 == 0) {
                        sendMessage(specs, data)
                        specs = ''
                    }
                }
                var keyboardButtons = [
                    { "text": "➡️ Track Product", "callback_data": `tr_message` },
                    { "text": "👌 Show Product", "callback_data": `get_message` },
                    { "text": 'ℹ️ Open in Flipkart', "url": url }
                ]
                specs += '\n\nℹ️ Generated by ' + botName
                sendButtonMessage(specs, data, null, keyboardButtons)
                if (searhNpull && i > 0) { return true }
            }
        } else {
            //sendReport(link)
            //sendReport(spec)
            sendReport('Issue captured from ' + data.message.from.first_name + ' (<code>' + data.message.chat.id + '</code>) :\nUndefined dspec for the command : \n' + data.message.text + '\n\nLink : ' + link)
            sendReport('JSON :\n<code>' + JSON.stringify(json) + '</code>')
            if (!searhNpull) { sendMessage('🙇‍♂️ Error occured!\nThe product you searched for is not adapted to our program.\nI am only be able to track product currently avaliable in Flipkart.\n\nReport has been sent and will be fixed as soon as possible!', data) }
        }
    } catch (e) {
        sendMessage('🙇‍♂️ Sorry! I failed to follow your command!\n\nA fix will be worked upon as soon as possible.', data)
        if (Error(e).message.split('message is too long').length > 1) {
            sendMessage('🤔 Specifications list is very long to handle!', data)
        }
        sendReport('Error occured from user <code>' + data.message.from.first_name + '</code> (<code>' + data.message.chat.id + '</code>)')
        sendReport(Error(e).message)
    }
}
